# ACÁ VA UN CONTROLADOR PARA TODOS LOS CONTROLADORES.
# EN VEZ DE HACER QUE DESDE MENÚ SE LLAME A TODOS LOS CONTROLADORES, (Y POR ENDE HACER UN CÓDIGO MENOS FLEXIBLE),
# ACÁ HACEMOS UNA CLASE QUE SE ENCARGUE DE CONECTARLOS (QUE ES MUCHO MEJOR, NO SE CENTRALIZA TODO EN MENUCONTROLLER)
# CREO QUE VA A SER UN STATE O ALGO ASÍ

# SE VA SETEAR EL ESTADO DEL CONTROLADOR ACTUAL:
#   PONELE:
# ESTADO = MENU
# ESTADO = JUEGO
# ESTADO = RANKING
# ETC...

# Y SE HACE LA CONECCIÓN ENTRE ELLOS, QUE MENÚ SE CONECTE CON TODOS DESDE ACÁ.


# https://chatgpt.com/c/673aca43-cd00-8007-af3b-d82a75c9dcb6
